Fix annoyances
Uninett/zinolib pull request #16
Opened 2023-05-11 12:03 UTC by hmpf

Best read commit by commit

2023-06-16 10:03 UTC, lunkwill42 requested changes
Mostly good to go, but naming things is hard and I'm not entirely convinced (yet)...

2023-06-16 11:00 UTC, hmpf commented on src/zinolib/ritz.py
> +    def _request(self, command, recv_buffer=4096, delim="\r\n"):
It doesn't read commands, it *sends* commands, reads the response, and returns the response. Statistically it seems to me this is usually named as a "request" that returns a "response", and now this code follows that de facto rule as well.

2023-06-16 11:16 UTC, lunkwill42 approved these changes
Alright, I'm convinced 👍

2023-06-16 11:16 UTC, lunkwill42 commented on src/zinolib/ritz.py
> +    def _request(self, command, recv_buffer=4096, delim="\r\n"):
Ah indeed, this is the function you were telling me about a while back! Thanks!

2023-06-16 12:04 UTC, hmpf commented
I'd like comments from @runborg as well before I merge.

2023-06-19 19:14 UTC, runborg approved these changes
As for the naming of _read_command, the original name is not a good name for it.. the new purposed name is way better :)

For the other changes they seems fine, no big comments.. :)

2023-06-22 08:25 UTC, merged